networks:
  dev:

services:
  nginx:
    build: 
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    

  backend:
    build:
      context: ./database
    networks:
      - dev

  frontend:
    build:
      context: ./olimpeducation
    ports:
      - '3000:3000'
    networks:
      - dev