networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
    networks:
      - dev
    

  backend:
    build:
      context: ./database
    networks:
      - dev

  frontend:
    build:
      context: ./olimpeducation
    networks:
      - dev