import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

export const metadata = {
  title: "OlimpEducation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  
  return (
    <html className="scpoll-smooth">
      <body className="bg-main text-white">
        <Header/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
