export const tags = [
    {id: 1, tagName: 'расчёт'}, 
    {id: 2, tagName: 'массовые доли'}, 
    {id: 3, tagName: 'угадайка'}, 
    {id: 4, tagName: 'неорганические реакции'}, 
    {id: 5, tagName: 'цепочки'}, 
    {id: 6, tagName: 'газы'}, 
    {id: 7, tagName: 'строение'}, 
    {id: 8, tagName: 'кристаллохимия'}, 
    {id: 9, tagName: 'практика'}, 
    {id: 10, tagName: 'кроссворды'}, 
    {id: 11, tagName: 'физхимия'}, 
    {id: 12, tagName: 'термохимия'}, 
    {id: 13, tagName: 'равновесие'}, 
    {id: 14, tagName: 'кинетика'}, 
    {id: 15, tagName: 'неорганическая химия'}, 
    {id: 16, tagName: 'благородные газы'}, 
    {id: 17, tagName: 'галогены'}, 
    {id: 18, tagName: 'халькогены'}, 
    {id: 19, tagName: 'халькогены2'}, 
    {id: 20, tagName: '5 группа'}, 
    {id: 21, tagName: '5 группа2'}, 
    {id: 22, tagName: '4 группа'}, 
    {id: 23, tagName: '4 группа2'}, 
    {id: 24, tagName: '3 группа'}, 
    {id: 25, tagName: '3 группа2'}, 
    {id: 26, tagName: '2 группа'}, 
    {id: 27, tagName: '1 группа'}, 
    {id: 28, tagName: 'побочные группы'}, 
    {id: 29, tagName: 'побочные группы2'}, 
    {id: 30, tagName: 'побочные группы3'}, 
    {id: 31, tagName: 'd-металлы'}, 
    {id: 32, tagName: 'd-металлы2'}, 
    {id: 33, tagName: 'd-металлы3'}, 
    {id: 34, tagName: 'd-металлы4'}, 
    {id: 35, tagName: 'лантаноиды'}, 
    {id: 36, tagName: 'актиноиды'}, 
    {id: 37, tagName: 'органическая химия'}, 
    {id: 38, tagName: 'алканы'}, 
    {id: 39, tagName: 'алкены'}, 
    {id: 40, tagName: 'алкины'}, 
    {id: 41, tagName: 'алкодиены'}, 
    {id: 42, tagName: 'ароматика'}, 
    {id: 43, tagName: 'спирты'}, 
    {id: 44, tagName: 'эфиры'}, 
    {id: 45, tagName: 'карбонильные соединения'}, 
    {id: 46, tagName: 'карбоновые кислоты'}, 
    {id: 47, tagName: 'азотсодержащие соединения'}, 
    {id: 48, tagName: 'биохимия'}
];
 